### ISSUE TITLE
Please provide an example of iterating over a a large results array

### ISSUE THREAD

**Issue by codecowboy** [visionmedia/batch#30]
I tried to use this package to iterate over a large array of results from a database call. I need to make an http request for each result. I gave up in the end. I am using Node 4.2.4.

Please provide an example which iterates over a large array of results and processes them in batches.

Your example:
```
var Batch = require('batch')
  , batch = new Batch;
 
batch.concurrency(4);
 
ids.forEach(function(id){
  batch.push(function(done){
    User.get(id, done);
  });
});
 
batch.on('progress', function(e){
 
});
 
batch.end(function(err, users){
 
});
```

Please show the creation of the ids array, what User and users are and where they are defined.

**Comment by leewaygroups** [comment]
I think your implementation may not be the best way to achieve your goal. 
Let's see part of your example:

`ids.forEach(function(id){
  batch.push(function(done){
    User.get(id, done);
  });
})`

Suppose ids.length = 1000000, then you'll be pushing 1000000 functions into batch which then makes 1000000 http calls. Not the best!

Depending on what you're trying to achieve and if you have control over the http end point  you're calling, a possible option is to consider redesigning that end point to take a collection/array of ids then you can make a single/fewer calls with subset of ids.

**Comment by codecowboy** [comment]
Thanks for your thoughtful reply. I didn't use batch in the end but thanks
