### ISSUE TITLE
defer function is always `setTimeout`

### ISSUE THREAD

**Issue by stephenmathieson** [visionmedia/batch#34]
it looks like we're checking for a `process` function [here](https://github.com/visionmedia/batch/blob/0.6.0/index.js#L16-L18), but it's an object:

```
$ node -pe 'typeof process'
object
```

would you take a patch fixing this?

/cc @dougwilson

**Comment by dougwilson** [comment]
Sure, please feel free to fix. Make sure it still functions in the browser that has no `process` defined :)
