### ISSUE TITLE
It would be nice to be able to set 'concurrency' when creating `batch` instance

### ISSUE THREAD

**Issue by MeoMix** [visionmedia/batch#36]
Currently I do:

```
      const batch = new Batch();
      batch.concurrency(20);
```

I would like to have the ability to do:

```
      const batch = new Batch({ concurrency: 20 });
```

**Comment by dougwilson** [comment]
This is a good idea :+1:  Would you be interested in making a pull request to.implement this?

**Comment by MeoMix** [comment]
Yeah, sure. I can try to whip something together ASAP.

**Comment by MeoMix** [comment]
wow, past me was an overly optimistic jerk for saying he'd put up a PR and not doing it.

thanks for finally getting around to this feature! great job :)
