### ISSUE TITLE
Module not found: Error: Can't resolve 'emitter'

### ISSUE THREAD

**Issue by ivands** [visionmedia/batch#41]
I'm trying to build a file for AWS lambda.
But because batch is required we get the following error:
```Module not found: Error: Can't resolve 'emitter'```

This is because `emitter` isn't a dependency in the package.json file.

Btw isn't this code broken???
```
try {
  var EventEmitter = require('events').EventEmitter;
  if (!EventEmitter) throw new Error();
} catch (err) {
  var Emitter = require('emitter');
}
```

The event emitter is exported as default:
```const EventEmitter = require('events');```

**Comment by dougwilson** [comment]
This package is both for Node.js and Component.js . You can see it is listed as a dependency in component.json . It should only attempt to require emitter if there is an error loading the events module which is built in to Node.js so does not need to be listed in package.json. I hope that helps.
