### ISSUE TITLE
Support bundling with `esbuild`

### ISSUE THREAD

**Issue by r-token** [visionmedia/batch#42]
Bundling with [esbuild](https://esbuild.github.io/) currently fails on this package due to an issue on [line 15 of index.js](https://github.com/visionmedia/batch/blob/47a9b1d1f5cd8e4b32dbb74a52aa968cf9b58480/index.js#L15). It references a package called "emitter" that esbuild cannot resolve, thus esbuild fails.

**Comment by dougwilson** [comment]
Hi @r-token thanks for opening this issue. I'm not familiar with `esbuild`, but `emitter` is a package on npm (https://www.npmjs.com/package/emitter) and it is a fallback to support browser builds with tools like browserify (https://github.com/visionmedia/batch/blob/master/package.json#L23). You may need to open an issue with `esbuild` or provide the specific steps we need to take to fix the issue.

**Comment by r-token** [comment]
Hi @dougwilson! No problem. I believe I actually know a straightforward way to resolve this, and have opened a PR accordingly. It's over at #43. Looking forward to discussing.

**Comment by r-token** [comment]
Thanks for merging this in @dougwilson! This is a huge help for us. Any timeline I can look forward to on when you'll be cutting a new NPM release that we can pull down that includes this change?

**Comment by alexchandel** [comment]
This issue is still present in the published package and affects many users.  Please push a new release.
